# Site settings
title: Code Responsibly
email: schalermthai@sprint3r.com
description: > # this means to ignore newlines until "baseurl:"
  Sharing is caring.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://schalermthai.github.io" # the base hostname & protocol for your site
github_username:  schalermthai
highlighter: rouge

# Build settings
markdown: kramdown
