# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'Code.log'
tagline:          ''
description:      'บันทึกการเรียนรู้เพื่อแบ่งปัน'
url:              http://schalermthai.github.io
baseurl:          /

author:
  name:           'Salah Chalermthai'
  url:            https://facebook.com/deans4j

paginate:         5

# Custom vars
version:          0.9

github:
  repo:           https://github.com/schalermthai
